#!/bin/sh

# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
commits=""

echo "Checking commit message..."
while read local_ref local_oid remote_ref remote_oid; do
  if [[ "${local_oid}" == "${zero}" ]]; then
    # Handle delete
    exit 0
  else
    if [[ "${remote_oid}" == "${zero}" ]]; then
      # New branch, examine all commits from develop
      range="develop..${local_oid}"
    else
      # Update to existing branch, examine new commits
      range="${remote_oid}..${local_oid}"
    fi

    commits=$(git log --pretty=format:"%s" "${range}")
  fi
done

# check commit message
if [[ -n "${commits}" ]]; then

  echo "${commits}" | while read -r commit; do
    echo "${commit}" | pnpx commitlint
    commitMessageStatus=$?

    if [[ $commitMessageStatus != 0 ]]; then
      echo "invalid commit message: ${commit}"
      exit 1
    fi
  done

  invalid=$?
  if [[ $invalid != 0 ]]; then
    echo "failed push because commit is invalid"
    exit 1
  fi
else
  echo "no commits"
  exit 1
fi

exit 0
