#!/bin/sh

# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')
commits=""

echo "Checking commit message..."
while read local_ref local_oid remote_ref remote_oid; do
	if test "$local_oid" = "$zero"; then
		# Handle delete
		:
	else
		if test "$remote_oid" = "$zero"; then
			# New branch, examine all commits from develop
			range="develop..$local_oid"
		else
			# Update to existing branch, examine new commits
			range="$remote_oid..$local_oid"
		fi

		# Check for WIP commit
		commits=$(git log --pretty=format:"%s" "$range")
		# commit=$(git rev-list --grep '^WIP' "$range")
		# if test -n "$commit"; then
		# 	echo >&2 "Found WIP commit in $local_ref, not pushing"
		# 	exit 1
		# fi
	fi
done

echo $comments

if [ -n "$comments"]; then
	echo "$commits" | while read -r commit; do
		echo "$commit" | pnpx commitlint
		commitMessageStatus=$?

		if [ $commitMessageStatus != 0 ]; then
			exit 1
		fi
	done
fi

exit 0
